version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_EXPORTER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://kafka1:29092,PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_EXPORTER://0.0.0.0:9100
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka1:29092,PLAINTEXT_HOST://kafka1:9092,PLAINTEXT_EXPORTER://kafka1:9100
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    volumes:
      - kafka1_data:/var/lib/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-net


  kafka2:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_EXPORTER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://kafka2:29093,PLAINTEXT_HOST://0.0.0.0:9093,PLAINTEXT_EXPORTER://0.0.0.0:9101
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka2:29093,PLAINTEXT_HOST://kafka2:9093,PLAINTEXT_EXPORTER://kafka2:9101
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    volumes:
      - kafka2_data:/var/lib/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka3:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_EXPORTER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://kafka3:29094,PLAINTEXT_HOST://0.0.0.0:9094,PLAINTEXT_EXPORTER://0.0.0.0:9102
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka3:29094,PLAINTEXT_HOST://kafka3:9094,PLAINTEXT_EXPORTER://kafka3:9102
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    volumes:
      - kafka3_data:/var/lib/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    command: ["--kafka.server=kafka1:9100","--kafka.server=kafka2:9101","--kafka.server=kafka3:9102"]
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - kafka-exporter
    networks:
      - kafka-net
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - kafka-net

  client:
    build: ./docker/client
    container_name: client
    tty: true
    volumes:
      - ./client:/app
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      - KAFKA_BROKERS=kafka1:29092,kafka2:29093,kafka3:29094
      - TOPIC_NAME=test-topic
    networks:
      - kafka-net
  
networks:
  kafka-net:
    driver: bridge

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:
  grafana_data:
    